import 'package:flutter/material.dart';
import 'colors.dart'; // 추가!

final ThemeData appTheme = ThemeData(
  useMaterial3: true,
  fontFamily: 'Pretendard',
  scaffoldBackgroundColor: LightColors.background,
  primaryColor: LightColors.primary,
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: LightColors.primary,
    onPrimary: LightColors.onPrimary,
    secondary: LightColors.secondary,
    onSecondary: LightColors.onSecondary,
    surface: LightColors.surface,
    onSurface: LightColors.onSurface,
    error: CommonColors.error,
    onError: Colors.white,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(
      fontSize: 36,
      fontWeight: FontWeight.w800,
      letterSpacing: -1.5,
      color: LightColors.display,
      height: 1.2,
    ),
    headlineLarge: TextStyle(
      fontSize: 28,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.5,
      color: LightColors.headline,
      height: 1.3,
    ),
    headlineMedium: TextStyle(
      fontSize: 24,
      fontWeight: FontWeight.w700,
      color: LightColors.headline,
      height: 1.3,
    ),
    headlineSmall: TextStyle(
      fontSize: 20,
      fontWeight: FontWeight.w600,
      color: LightColors.onSurface,
    ),
    bodyLarge: TextStyle(
      fontSize: 17,
      fontWeight: FontWeight.w500,
      color: LightColors.body,
      height: 1.6,
      letterSpacing: 0.1,
    ),
    bodyMedium: TextStyle(
      fontSize: 15,
      fontWeight: FontWeight.w400,
      color: LightColors.bodyMedium,
      height: 1.5,
    ),
    bodySmall: TextStyle(
      fontSize: 13,
      fontWeight: FontWeight.w400,
      color: LightColors.bodySmall,
    ),
    labelLarge: TextStyle(
      fontSize: 15,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.3,
      color: LightColors.label,
    ),
    labelMedium: TextStyle(
      fontSize: 13,
      fontWeight: FontWeight.w500,
      color: LightColors.label,
    ),
    labelSmall: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      color: LightColors.labelSmall,
    ),
  ),
  appBarTheme: const AppBarTheme(
    backgroundColor: LightColors.appBar,
    scrolledUnderElevation: 0,
    elevation: 0,
    titleTextStyle: TextStyle(
      fontFamily: 'Pretendard',
      fontWeight: FontWeight.w700,
      fontSize: 20,
      color: LightColors.onBackground,
      letterSpacing: -0.3,
    ),
    iconTheme: IconThemeData(color: LightColors.primary),
    actionsIconTheme: IconThemeData(color: LightColors.primary),
    centerTitle: true,
    shadowColor: Colors.transparent,
  ),
  cardTheme: CardThemeData(
    elevation: 0,
    color: LightColors.surface,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(20),
    ),
    margin: const EdgeInsets.all(12),
    shadowColor: LightColors.primary.withOpacity(0.08),
    surfaceTintColor: Colors.transparent,
  ),
  floatingActionButtonTheme: FloatingActionButtonThemeData(
    backgroundColor: LightColors.fabFill,
    foregroundColor: Colors.white,
    elevation: 4,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(16),
    ),
  ),
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: LightColors.inputFill,
    contentPadding: const EdgeInsets.symmetric(vertical: 16, horizontal: 20),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: BorderSide(color: LightColors.divider, width: 1.5),
    ),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: BorderSide(color: LightColors.divider, width: 1.5),
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: const BorderSide(color: LightColors.primary, width: 2),
    ),
    hintStyle: const TextStyle(
      color: LightColors.bodySmall,
      fontSize: 15,
      fontWeight: FontWeight.w400,
    ),
    labelStyle: const TextStyle(
      color: LightColors.primary,
      fontWeight: FontWeight.w500,
    ),
  ),
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: LightColors.primary,
      foregroundColor: Colors.white,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      textStyle: const TextStyle(
        fontWeight: FontWeight.w700,
        fontSize: 16,
        letterSpacing: 0.2,
      ),
      elevation: 0,
      shadowColor: LightColors.primary.withOpacity(0.3),
      padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
    ),
  ),
  outlinedButtonTheme: OutlinedButtonThemeData(
    style: OutlinedButton.styleFrom(
      foregroundColor: LightColors.primary,
      backgroundColor: Colors.transparent,
      side: const BorderSide(color: LightColors.primary, width: 1.5),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 16),
      padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
    ),
  ),
  dividerTheme: const DividerThemeData(
    color: LightColors.divider,
    thickness: 1,
    space: 1,
  ),
  bottomNavigationBarTheme: const BottomNavigationBarThemeData(
    backgroundColor: LightColors.appBar,
    elevation: 0,
    selectedItemColor: LightColors.primary,
    unselectedItemColor: LightColors.bodySmall,
    selectedLabelStyle: TextStyle(fontWeight: FontWeight.w700, fontSize: 12),
    unselectedLabelStyle: TextStyle(fontWeight: FontWeight.w500, fontSize: 11),
    type: BottomNavigationBarType.fixed,
    showUnselectedLabels: true,
  ),
);

final ThemeData appThemeDark = ThemeData(
  useMaterial3: true,
  fontFamily: 'Pretendard',
  scaffoldBackgroundColor: DarkColors.background,
  primaryColor: DarkColors.primary,
  colorScheme: const ColorScheme.dark(
    primary: DarkColors.primary,
    onPrimary: DarkColors.onPrimary,
    secondary: DarkColors.secondary,
    onSecondary: DarkColors.onSecondary,
    surface: DarkColors.surface,
    onSurface: DarkColors.onSurface,
    error: CommonColors.error,
    onError: Colors.black,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(
      fontSize: 36,
      fontWeight: FontWeight.w800,
      letterSpacing: -1.5,
      color: DarkColors.display,
      height: 1.2,
    ),
    headlineLarge: TextStyle(
      fontSize: 28,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.5,
      color: DarkColors.headline,
      height: 1.3,
    ),
    headlineMedium: TextStyle(
      fontSize: 24,
      fontWeight: FontWeight.w700,
      color: DarkColors.headline,
      height: 1.3,
    ),
    headlineSmall: TextStyle(
      fontSize: 20,
      fontWeight: FontWeight.w600,
      color: DarkColors.display,
    ),
    bodyLarge: TextStyle(
      fontSize: 17,
      fontWeight: FontWeight.w500,
      color: DarkColors.body,
      height: 1.6,
      letterSpacing: 0.1,
    ),
    bodyMedium: TextStyle(
      fontSize: 15,
      fontWeight: FontWeight.w400,
      color: DarkColors.bodyMedium,
      height: 1.5,
    ),
    bodySmall: TextStyle(
      fontSize: 13,
      fontWeight: FontWeight.w400,
      color: DarkColors.bodySmall,
    ),
    labelLarge: TextStyle(
      fontSize: 15,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.3,
      color: DarkColors.label,
    ),
    labelMedium: TextStyle(
      fontSize: 13,
      fontWeight: FontWeight.w500,
      color: DarkColors.label,
    ),
    labelSmall: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      color: DarkColors.labelSmall,
    ),
  ),
  appBarTheme: const AppBarTheme(
    backgroundColor: DarkColors.appBar,
    elevation: 0,
    scrolledUnderElevation: 0,
    titleTextStyle: TextStyle(
      fontFamily: 'Pretendard',
      fontWeight: FontWeight.w700,
      fontSize: 20,
      color: DarkColors.onSurface,
      letterSpacing: -0.3,
    ),
    iconTheme: IconThemeData(color: DarkColors.primary),
    actionsIconTheme: IconThemeData(color: DarkColors.primary),
    centerTitle: true,
    shadowColor: Colors.transparent,
  ),
  cardTheme: CardThemeData(
    elevation: 0,
    color: DarkColors.surface,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(20),
    ),
    margin: const EdgeInsets.all(12),
    shadowColor: DarkColors.primary.withOpacity(0.1),
    surfaceTintColor: Colors.transparent,
  ),
  floatingActionButtonTheme: FloatingActionButtonThemeData(
    backgroundColor: DarkColors.fabFill,
    foregroundColor: DarkColors.onPrimary,
    elevation: 4,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(16),
    ),
  ),
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: DarkColors.inputFill,
    contentPadding: const EdgeInsets.symmetric(vertical: 16, horizontal: 20),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: BorderSide(color: DarkColors.divider, width: 1.5),
    ),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: BorderSide(color: DarkColors.divider, width: 1.5),
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: const BorderSide(color: DarkColors.primary, width: 2),
    ),
    hintStyle: const TextStyle(
      color: DarkColors.bodySmall,
      fontSize: 15,
      fontWeight: FontWeight.w400,
    ),
    labelStyle: const TextStyle(
      color: DarkColors.primary,
      fontWeight: FontWeight.w500,
    ),
  ),
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      backgroundColor: DarkColors.primary,
      foregroundColor: DarkColors.onPrimary,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      textStyle: const TextStyle(
        fontWeight: FontWeight.w700,
        fontSize: 16,
        letterSpacing: 0.2,
      ),
      elevation: 0,
      shadowColor: DarkColors.primary.withOpacity(0.4),
      padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
    ),
  ),
  outlinedButtonTheme: OutlinedButtonThemeData(
    style: OutlinedButton.styleFrom(
      foregroundColor: DarkColors.primary,
      backgroundColor: Colors.transparent,
      side: const BorderSide(color: DarkColors.primary, width: 1.5),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 16),
      padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
    ),
  ),
  dividerTheme: const DividerThemeData(
    color: DarkColors.divider,
    thickness: 1,
    space: 1,
  ),
  bottomNavigationBarTheme: const BottomNavigationBarThemeData(
    backgroundColor: DarkColors.appBar,
    elevation: 0,
    selectedItemColor: DarkColors.primary,
    unselectedItemColor: DarkColors.bodySmall,
    selectedLabelStyle: TextStyle(fontWeight: FontWeight.w700, fontSize: 12),
    unselectedLabelStyle: TextStyle(fontWeight: FontWeight.w500, fontSize: 11),
    type: BottomNavigationBarType.fixed,
    showUnselectedLabels: true,
  ),
);
